<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Neel Technologies</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
						color: #333;
						margin: 0;
						padding: 40px;
						background: #f8fafc;
					}
					h1 { color: #1e3a8a; }
					table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }
					th { background: #1e3a8a; color: white; text-align: left; padding: 12px 15px; }
					td { padding: 10px 15px; border-bottom: 1px solid #e2e8f0; }
					tr:hover { background: #f1f5f9; }
					a { color: #2563eb; text-decoration: none; }
					a:hover { text-decoration: underline; }
					.footer { margin-top: 20px; font-size: 12px; color: #64748b; }
				</style>
			</head>
			<body>
				<h1>XML Sitemap</h1>
				<p>This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
				<table>
					<thead>
						<tr>
							<th>URL</th>
							<th>Priority</th>
							<th>Last Modified</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<td>
									<a href="{sitemap:loc}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td><xsl:value-of select="sitemap:priority"/></td>
								<td><xsl:value-of select="sitemap:lastmod"/></td>
							</tr>
						</xsl:for-each>
					</tbody>
				</table>
				<div class="footer">
					Generated by Neel Technologies Sitemap Generator
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
